server:
  port: 8001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bs_platform_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 990622

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  jackson:
    default-property-inclusion: non_null #设置json不返回null值字段

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:2333/token/current/get
      id: bsp-user

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neusoft.bsp.user.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true #map空值不传问题

management:
  endpoints:
    web:
      exposure:
        include: '*'