server:
  port: 2333

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 990622

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neusoft.bsp.oauth.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true